export const appConfig = {
  TESTNET: true,
  AA_ADDRESS: "FQQLTDJGGTXKCOHYOR4RZYHN2VE3QZ72",
  MIN_BALANCE: 1e8, // TODO: 50e9 for mainnet
  MIN_LOCKED_TERM_DAYS: 1, // TODO: 365 for mainnet
  DISCORD_BOT_URL: "obyte:Ama48/uKO+/Tjv28zFKwElBO4SEQNuWAM1VPJkl4DTZO@obyte.org/bb#0000",
  TELEGRAM_BOT_URL: "obyte:A1KwcOAZSWwBnXwa1BKfmhEP2yow1kaUuoi5A6HLOzJZ@obyte.org/bb#0000",
  REAL_NAME_BOT_URL: "obyte:___________@obyte.org/bb#0000",


  NEXT_PUBLIC_CITY_AA_ADDRESS: "XUXPOHYSH6PHQBTM32ZIJX3RHWBJHX4L",
  NEXT_PUBLIC_DISCORD_ATTESTOR: "EJC4A7WQGHEZEKW6RLO7F26SAR4LAQBU",
  NEXT_PUBLIC_TELEGRAM_ATTESTOR: "WMFLGI2GLAB2MDF2KQAH37VNRRMK7A5N",
} as const;